fix bug where queuePosition sort in config is ignored
tremc/tremc pull request #66
Opened 2020-09-20 15:51 UTC by gangelop

Queue was implemented in rpc version 14. The code checked for rpc
version >= 14 and tried to then enable queuePosition sort but this
happened after the config was parsed. Checking before the config is
parsed is not possible because the connection to the server is not
established that early.

This fix removes the check entirely. This means that for users who use
queuePosition sort in their configs and then downgrade for some reason
to an older transmission-daemon version, tremc will likely crash with an
exception.

This will not break any existing configs of old installations and for
this reason I consider it an acceptable fix, in the interest of time and
less code complexity.

fixes #64

2020-09-20 16:10 UTC, MatanZ requested changes
I believe that the code in line 1289 should remain, but reversed: remove queuePosition if old daemon. It should probably also change the sort order to 'name' if it is 'queuePosition', since otherwise the sort will attempt to access non-existing key 'queuePosition'.

2020-09-20 17:29 UTC, MatanZ requested changes
gconfig.sort_orders needs to be changed only if the sort order is queuePosition. Otherwise, with older daemon order will always be name, regardless of config file setting.

2020-09-20 17:30 UTC, gangelop commented
yeah that's dumb. I think I've had enough computer for today.

2020-09-21 22:08 UTC, gangelop commented
Since the first commit lgtm I'm going to merge it to fix the current bug. If you can and want to figure out how to re-include the check for the corner case of a downgrade, feel free to open a PR.

2020-09-21 22:08 UTC, closed without merging